# Generated by Django 5.0.1 on 2024-01-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactmessage_delete_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='ContactMessageModel',
        ),
    ]
