# Generated by Django 5.0.1 on 2024-01-03 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_contactmessage_contactmessagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessageModel',
        ),
    ]
